### ISSUE TITLE
[Backend] Create custom error class for error handling

### ISSUE THREAD

**Issue by shamskhodary** [CA-G12/Share-Us#25]

**Comment by aaamra** [comment]
it's a great idea to make our custom error

but i want to add another thing 

in our controller we are using promises 
and promises may throw some errors 
because of  that we handle it with `try` & `catch` blocks or with `.catch` syntax

so i suggest you to make a wrapper for our all controllers
in that wrapper we handle all the errors with `try` & `catch` block

after that we pass our controller to this wrapper and then he executes the controller

may be it will look like this in our routes
```js
import allEvents from '../controllers/allEvents'

router.get('/events', errorHandler(allEvents));
```

and the `errorHandler` may look like this
```js
const errorHandler = (controller) => {
     return async (req, res, next) => {
          try{
              await controller(req, res, next)
          }catch(err){
              // here we may send our errors or we just make next(err) and then handle it in the errors middleware
          }
     }
}
```
